#!/bin/bash
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射能除染
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民の帰還
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/生活の再建
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興予算の大幅見直し
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県内に100万kW級の石炭ガス化複合発電（IGCC）の新設
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県内での1万kW級のメガソーラー発電所を複数箇所に展開
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県内で最大2000人規模の雇用創出
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島原発から東京への送電線の利用
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災復興財源確保
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災がれき処理
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災と東京電力福島第一原発事故からの再生と次代へつなぐ共同の実践
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県内ＪＡを合併再編する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/衆議院選挙立候補予定者が復興への道筋を示す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難生活の基盤整備
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災復興祈念八重桜植樹祭を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災の被災者のための集会所「みんなの家」を作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災道路の整備を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/南三陸町の復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/南相馬市の復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災で激減した乗客を呼び戻す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/岩手県の復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/陸前高田市の復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「不良建設業者」を排除する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興予算の配分を被災地を最優先にする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災の復旧工事を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第１原発事故の避難区域見直しを行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難区域の解除
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東北に観光客を誘致する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島の特産品のすばらしさをＰＲする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難住民の帰還
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/閖上の復興計画の遂行
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/再生を目指す複数の中小企業を支援する「グループ補助金」の充実
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/雇用のミスマッチの解消
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力福島第1原発事故に対応する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/村民の帰村
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災復興事業を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/仙台市の災害危険区域外の津波浸水地域住宅の再建
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災の津波で浸水した災害危険区域外の被災者への住宅再建支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/特殊ビデオカメラを除染作業で利用する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「指定廃棄物」最終処分場を高萩市上君田の国有林に造る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/中間貯蔵施設を建設する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/早期除染
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/TPP参加
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/衆院解散
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/政権の維持
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大熊町に戻る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民帰還の作業拠点となる宿泊施設の設置
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/町民の絆を保つ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/帰還可能地域の住民に対する意識調査を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/教育環境の整備
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地の学生向けにインターネット上で教育や就職などの支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/農業の復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島ブランドの信頼回復
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災した農家支援
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/野生動物による農業被害を阻止する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/営農再開
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/漁業の復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ノルウェー型の漁業・水産業の資源管理を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/底引き網漁の漁場を確保する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/本格操業
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/コウナゴ漁の本格操業
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/雇用の確保
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/NPO法人大雪りばぁねっと。活動停止に対する対策を講じる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/広野工場の求人
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/本店オフィスサービスセンター移転により雇用を創出する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/収入の確保
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/消費税増税前に再建する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者の就労支援
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/防災集団移転先の宅地を決める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/生活の早期再建
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/自営業者への支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災した零細事業者の二重ローン問題を解消する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/２０１１、１２年度予算のうち、１１府省の３５事業１６８億円分の執行を停止する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/１３年度以降は被災地の復興と被災者の生活再建のために限る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/平成２５年度復興予算編成
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島原発事故責任追及と補償
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島原発事故第２次集団告訴の立件
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/公害犯罪処罰法違反の適用
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/水素爆発で原子炉建屋を損壊させた業務上過失激発物破裂の適用
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「津波や過酷事故の対策を怠り事故を招き、放射性物質を排出させた」などとする業務上過失致死傷の適用
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/受刑者の就労支援への復興支援予算の支出
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/減災に向けた広報・啓発への復興支援予算の支出
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/事業仕分
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/JT株を2012年度内までに売却
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/全国の国家公務員宿舎の使用料（賃料）を平均5割引き上げる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/売却益を東日本大震災の復興財源に充てる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/2012年3月までに震災がれきの53％を処理する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/Ｍｉｎｄ－１日本プロジェクトの継続
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/岩手県陸前高田市へと所属選手、クラブスタッフを派遣し現地でサッカー教室を開催
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/陸前高田市から被災児童やその保護者などを招待した川崎修学旅行の実行
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/Ｍｉｎｄ－１ニッポンプロジェクトの街頭募金活動
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ぎんなんを販売する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災復興支援金を送る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/生活再建支援金を被災者に支給する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/除染対策
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/再生可能エネルギーの利活用
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/きめ細かい放射性物質検査の実施
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/浮体式洋上風力発電所を建設する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/環太平洋連携協定（ＴＰＰ）交渉参加反対
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難先との交流を深める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民主導で人ありきの復興住宅を考える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/生活環境の基盤整備
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援金を受け取る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射性物質の分布状況を簡単に観測、動画撮影できる特殊ビデオカメラを開発
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/除染作業の速度を上げる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/汚染土壌を保管する中間貯蔵施設建設候補地の見直し
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/候補地選定の受け入れ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力福島第１原発事故に伴う損害賠償として東京電力が２６８５万円を払う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力が福島第一事故の責任を取る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力が避難者に対して補償をする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原発事故による賠償請求の相談に乗る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原発事故損害賠償の説明会・相談会を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民が除染に参加する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/公費負担によるマンション敷地の除染
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/除染業者を認定する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興を目指す福島県の声を発信
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/南三陸町の窮状を発信する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/次代を担う２０～３０代が復興に向けた考えを語り合う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/2012年11月下旬に取りまとめを発表する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災のことをわすれない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災の記憶を保つ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援金を適正に支給する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災による損壊規模を判定する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/生活再建支援金を公平に支給する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支給済み支援金の返済を求める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支給済み支援金を返済しない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/事故後４カ月間の個人の行動記録に基づいて調べ、外部被曝を推計する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故による放射能汚染の実態を調査する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被爆による健康被害に対応する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被ばく医療
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島の住人の被ばく医療や健康管理を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力福島第１原発事故による放射線の影響を調べる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/再生していく故郷を望める場所を作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災したコミュニティの絆を保つ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先に置いて、移動元のコミュニティーが維持・継続できるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/町としてのコミュニティーを維持する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/津波の塩害で廃材となるはずだったスギの丸太１９本を柱に使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/船ごとに漁獲枠を設定し、監視のため通信衛星漁船管理システム（ＶＭＳ）の搭載を義務付ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/魚種ごとに漁獲量を定める日本の「ＴＡＣ制度」をやめる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/三陸沿岸道を整備する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/三陸沿岸道の内、宮古中央－田老北間を整備する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/宮古市内で目に見える復興を進める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/道路整備事業を短期間で着工する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復旧・復興事業に携わる職員の長期派遣要請
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/公共工事関連の技術職員を確保する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/南三陸町に世間の注目を集める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/南三陸町に支援や義援金を集める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/定期的に南三陸町町長会見を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/南三陸町防災庁舎を解体する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/１０月末に南三陸町防災庁舎を解体する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/南三陸町防災庁舎解体時期を延期する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/新米を買う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/新米を小池長沼仮設住宅で配布する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/山古志小の児童が寄せた応援メッセージを贈る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/旧山古志村で闘牛場で開設準備を手伝った南相馬市の避難者と交流する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者を元気づける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「相馬野馬追太鼓」の演奏会を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/自分たちの復興を見せることで、被災者に勇気を与える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先での被災者と地域住民との交流の場を設ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災前に行っていた「相馬野馬追太鼓」の活動を再開する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災前の伝統を守る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/塩作り釜を復活させる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/イノシシを捕獲する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/捕獲したイノシシを食用として出荷する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/イノシシの個体数調整を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/仮説住宅でも猟銃を保管する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/出荷可能なセシウムの暫定基準値を1キロ100ベクレルとする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/イノシシ1匹につき5000円の補助金を出す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/狩猟登録者数を確保する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災から2年以内にイノシシの個体数調整を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「津波避難誘導マニュアル」を作成する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「津波避難誘導マニュアル」に基づいた訓練を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/訓練で問題点が見つかればマニュアルを見直し、実践的なものにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災に伴う津波の教訓を生かす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/災害対策を整備する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/銚子海洋研究所の事務所を移転する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/乗客の受け付けや案内をしやすくする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/政府系金融機関の震災対応融資を受ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興住宅（災害公営住宅）のあり方を考えるシンポジウムを開催する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興住宅への移転後も仮設住宅で醸成されたコミュニティーを維持する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民発のアイデアを行政につないでいく仕組みを作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大槌町で岩手県と大槌町の合同の追悼式を開く
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/岩手県民全体で思いを共有する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/岩手県の復旧・復興の歩みをさらに力強くする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/合同の追悼式の場所や規模を決める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/車椅子の人でもお年寄りでもみんなが使いやすい街を目指す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/親を亡くした子供たちが夢を追いかけられる環境を守る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/陸前高田市を応援してもらう
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地を応援してもらう
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/岩手、宮城、福島の３県に新設された建設業者の営業所を中心に立ち入り検査する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/下請け業者への代金支払いを調べる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「一括下請け（丸投げ）」の有無を調べる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/技術者を適正に配置しているかを調べる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/法令違反のあった業者には指導や勧告、営業停止などの処分を検討する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災復興予算を適正に使用する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力福島第1、第2原発に対する核燃料税を廃止する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県内原発の全基廃炉
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興予算の計上に関する新しい基準を決める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興予算の計上に関する新しい基準を今月末に決める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/全国防災対策の対象事業を絞り込む
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/対象事業を復興支援予算の対象とする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/対象事業を復興支援予算の対象としない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/全国の津波対策の強化に復興予算を使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/全国の耐震性の低い学校の耐震化に復興予算を使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/道路などの防災対策に復興予算を使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国の庁舎の耐震化に復興予算を使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/広報啓発活動費に復興予算を使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ふくしま国際医療科学センターを設立する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/災害・地域医療の人材育成機関を設立する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/先端臨床研究センターを設立する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被ばく線量を減らす方法などを調査研究する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/高度ながんの画像診断を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/平成１４～１６年度に人材育成機関、先端臨床研究センターや新病棟など計４棟を建設する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ＰＥＴ－ＭＲＩを導入する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/健康不安を解消する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/健康への不安が少なくなるよう、丁寧に説明する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/２０１１年の医療施設調査・病院報告を発表する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/津波や原発事故の影響を発表する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/任期付き都道府県・政令市ＯＢを募集する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/任期付き都道府県・政令市ＯＢ応募結果を発表する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第１原発事故の避難区域再編案を2012年内に決める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/浪江町住人の意見を聞く
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第１原発事故の避難区域再編を2013年3月から実施する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発の現状を発表する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第1原発の地下にたまった放射能汚染水を浄化処理する第2セシウム吸着装置の建屋から、176リットルの汚染水が建屋外壁に隣接するコンクリート敷地上に漏れた原因を調査する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発の現状を知る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故に対する対応を決める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/１８歳以下の約３６万人を対象に甲状腺検査を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射線とがんの関係を調べる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射線と甲状腺がんの関係を丁寧に調べていく
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国家公務員宿舎5046カ所（約5．6万戸）を廃止し、跡地の売却で約1700億円を捻出する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/2016年度末までに宿舎を取り壊し、跡地を売却する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/宿舎の大幅減で維持管理費などの経費を将来にわたり圧縮する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興支援プロジェクト「行こうよ！東北」を実施する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/新たな旅行商品を作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大規模な研修を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/参加各社は視察後、１２月末までに東北旅行の企画案をまとめる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地のボランティア活動を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東北の観光関係者との交流会を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東北各県が誘客に力を入れる計２８コースを巡る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/来年１月にコンテストを実施し、優秀な企画案の商品化を検討する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東北の観光復興を業界全体で支援する意識を共有する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/研修参加を通じて東北がどんな思いで復興に取り組んでいるか、各担当者が肌で感じる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興支援イベント「心の絆応援プロジェクト」を開催する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地の子どもたちと船橋の子どもたちの間に絆が生まれる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもたちの助け合う心、優しい心を育む
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東北3県の物産販売を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地居住の子どもたちの支援
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/沖縄県内全６地区の小中学校と県立高校、特別支援学校の計１４カ所で給食の放射性物質検査を実施する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/沖縄県内の学校の保護者の安心を得る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発廃炉
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第１原発３号機から使用済み燃料を取り出す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射性物質の拡散を防ぐため、原子炉建屋に１５００トンの鉄骨カバーを設置する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/取り出し後の使用済み燃料の移送先を決定する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/使用済み燃料の最終処理の方法を決める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発廃炉に向けた計画を立てる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発の廃炉処理を安全に行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/使用済み燃料を早く降ろして、乾式キャスク（金属製の容器）に移す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/プールの冷却水を喪失した場合を踏まえ、不測の事態に備えて作業を行うことを東電に要請する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発廃炉に向けた準備を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/遠隔操作によるクレーン作業訓練を2012年11月中に開始する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「福島いわき復興物産展」を開催する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射能汚染の風評被害を払しょくする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/清泉女学院岩手県大槌町復興支援プロジェクト活動報告会を開催する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大槌町社会福祉協議会の菊池政志氏の講演を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大学の活動を広報する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地の情報を伝える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/衆議院選挙を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/選挙にかかわる人員を確保する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ポスター掲示板の設置作業を行う業者を確保する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/投票箱を購入する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/衆院解散後に予算の裏付けを取る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興工事を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ツアー客に塩作りを体験してもらう
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/塩作りを産業として復活させる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/旅行客を呼び込む
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災住宅の解体・撤去を本年度内に完了する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災で被災した住宅を公費で解体する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/浸水地域の堤防を仮復旧させた上で水を抜く
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/解体を希望する被災住宅などの所有者に早期の申請を呼び掛ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/公費解体の期限の延長を求める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/南相馬市小高、原町両区の旧警戒区域にある県、市所有の７つの農業用排水機場を直轄事業で復旧させる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/農業用排水機場の早期復旧
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県への観光客を増やす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/会津を観光視察
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/会津若松への観光客を増やす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/外国人観光客の落ち込みを食い止める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/会津の魅力を国民に伝える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/会津や県職員が台湾を訪れ直接ＰＲする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「東日本大震災・ふくしま復興祈念特別演奏会」を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/入場料を震災復興の義援金に充てる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/音楽で福島県を元気づける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/遠隔操作が可能な四足歩行ロボットを開発
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第１原発内に東芝のオペレーターを配置して作業を進める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力福島第１原発内で作業を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/閖上地区の区画整理事業の計画人口について、当初の５５００人から３０００人に下方修正
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/（１）計画人口５５００人の根拠（２）事業規模と土地利用計画（３）非居住区域となる公園用地の規模－などについて詳細な説明を求める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/閖上地区復興事業地内に居住したくない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災前居住者と同じ5500人を確保し小中学校や医療機関、商業施設などの維持ができるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/自地域に復興支援予算を確保する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/公平に復興事業を遂行する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国土交通省のガイドラインをクリアできる3000人の人口を目指す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/選挙で議席を伸ばし、政権を担う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/脱原発の第３極勢力の結集
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「第三極」として選挙協力を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「脱原発」を旗印とする新党の結成
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/脱原発を掲げる政党を含む政治勢力の受け皿となる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/新党結成
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/みどりの風の新党参画
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/脱原発
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/環太平洋経済連携協定（ＴＰＰ）参加反対
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/消費増税反対
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/無所属の新党参画
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/嘉田由紀子滋賀県知事を新党党首に
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/選挙区調整はじゃんけんで決めてもいい
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/選挙区調整を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/じゃんけん発言に不快感
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/無理な選挙区調整はしない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/日本維新の会の候補に出馬を譲らない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/みんなの党の政策を守る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/今後の調整を見守る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/合流しない方がいい
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/もっと政策を国民に理解してもらう姿勢を見せてほしい
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/合流・合流反対の茶番は見たくない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/みどりの風との連携
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/脱原発を掲げる政党幹部と連携の模索
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国民の生活が第一の小沢一郎代表との連携
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/新党名にも「未来」を入れる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/対談を報道陣公開の下で行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/新党結成の経過を語る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/嘉田由紀子が小沢一郎と対談をする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/嘉田由紀子が新党を結成する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/注目を集め、票につなげる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「全国経済同友会代表幹事円卓会議」を被災地で開催する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「全国経済同友会代表幹事円卓会議」を福島市で開催する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災、東京電力福島第1原発事故を風化させない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一事故の風化を防ぐ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/除染や廃炉へ向けた作業について説明する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「福島復興本社」の新設
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原発の安全対策について説明する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/廃炉処理の現状を説明する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発の安全性を知る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発の廃炉処理への不安を払拭する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県川内村で工場の操業を始める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県川内村の村民を50人雇う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/当面は３０人規模で操業
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/求人に応募しない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/就労よりも賠償金をあてにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/求人充足率の向上
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/他電力４社から緊急の応援融通
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/１２月の需要期に向け、発電設備の定期検査を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/気象庁の予報から暖房需要の消費電力を推算
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/寒いので暖房を使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第１原発事故で発生した「指定廃棄物」の最終処分場を造る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/決起集会を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/選定の白紙撤回に向けた市民の士気の向上
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力福島第１原発２０キロ圏内に置き去りにされた動物たちの現状を伝える写真展
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地で動物の救護活動
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/現地の動物は数が減っている上、保護しにくくなっている現状を伝える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/無料のがん検診を受ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/2011年12月の事故収束宣言以降の作業者には無料のがん検診を提供しない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故収束宣言を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発で原発事故後の作業者に無料のがん検診を提供する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/１００ミリシーベルトを超える放射線を浴びた人は、生涯にわたり年１回、無料でがん検診を受けられる制度を作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/不安を感じる人の相談に乗る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故後の作業者２万４１１８人のうち、無料がん検診対象者は3.7％であることを伝える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故収束をアピールする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興住宅を整備する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/町外コミュニティー入居のアンケートを取る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地へ帰還するための住宅確保への支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原発ゼロ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大阪府市エネルギー戦略会議が原発ゼロへのシナリオを作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/維新の会に抗議する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京都専修学校各種学校協会の震災復興予算不正使用金の全額返納と事業受託の辞退
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/インターネット上で教育や就職などの支援を行う活動に震災復興予算を使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災に対応した雇用創出基金事業を延長する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者へのジョブトレーニング支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者を雇用した企業へ助成金・補助金を出す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/護岸工事を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東通原発断層の再調査
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原発の安全性を確認する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東通原発の再稼働
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/養殖魚を活用して被災地を応援する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/魚介類の全量放射能検査できる機械の開発
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/相馬のノリ養殖の復活
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射性物質の自主検査に要した費用を東京電力に損害賠償請求する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/安全な水産資源を消費者に届ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/漁業再興のために番小屋を建設する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/漁業者の復興がかなうまで支援を続ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島に廃炉の国際拠点
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「ＩＡＥＡ緊急時対応能力研修センター」を福島県内に設置
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民の健康管理
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射線災害医療の作業グループを設置
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原子力対策で日本が主導的役割を果たす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/IAEAの知識を福島に生かす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原発をめぐる情報の透明性強化
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原発の新規導入国の安全性確保
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/アジア太平洋地域での原子力事故に備える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/会津若松市に仮園舎を置く大熊幼稚園に絵本１５０冊寄贈する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/読み聞かせに力を入れる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地を支援する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「復興なみえ町十日市祭」を開催する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/浪江町の風物詩を再現する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/浪江町内各地の神楽や田植踊りなどの伝統を維持する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/相馬焼の伝統を保つ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/全国に避難した浪江町の小学生が祭りに参加する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/会場から同市小沢工業団地に開設された大堀相馬焼の工房行きのバスを運行する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/法テラスふたばを広野町に設置する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/いわき市などに避難する被災者が利用する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動相談車を配備する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原子力損害賠償紛争解決センターへの申し立て依頼を受け付ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者に賠償についての知識を伝える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/刑事事件以外の法律相談を受け付ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援法の具体的な施策を充実させる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援対象地域を福島県全域にする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国が支援法について周知徹底を図る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国が支援法について対象住民に対する意識調査を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国が子ども・被災者支援法専門窓口を設置する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援対象住民が移動しても支援を受けられるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもを連れて県外に避難する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/母子・父子で避難している被災者への支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもを被爆から守る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県民を分断しない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/安定した支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/風評被害から県民を守る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島への転入者を保護する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島の復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/地域の生活と環境を回復する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/これから生まれてくる被災者の子どもを守る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/法的に求償が困難あるいは不可能な損害に対する支援は具体的施策に盛り込まない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/除染に関する知識・技術に関する説明や研修を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「除染の日」制度を作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/全国的な支援を得る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射能に対する正確な知識を国民に啓発する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/医療や商店の整った地域に帰還する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民が帰還した地域に出店・開業する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/帰還可能地域での事業再開や新規進出に対する資金援助を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射線量が上昇した地域で生活を継続する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民それぞれが適切な放射線防護を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/空間線量等の情報公開を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/精密な線量調査を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/内部被ばくを回避する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/自己の外部被ばくの状況を正しく把握する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ガイガーカウンターやガラスバッジを配布する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ガイガーカウンターの無料校正機関を各地に広く設置する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ガラスバッジを改良する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/飲食品の放射性物質含有量検査等の情報提供を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/全国の産品の放射性物質含有量検査結果を誰でも検索できるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島県だけでなく、全国の産品の放射性物質含有量検査の全量・全袋検査を実施する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射性物質含有量が、消費者が購入する場面で簡単に確認できるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援対象地域内に子どものための屋内施設を確保する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもの発育権を保障する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/総合子ども施設を新設する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/民間の体育館や遊園地を子ども・被災者支援施設として一般無料開放できるよう助成する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/週末避難の支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/週末避難のための交通費の負担軽減
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国営・公営施設の利用負担軽減
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/保養地に置いて外部被ばく検査を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもの親に保養休暇制度を創設する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射線量の低い地域での体験活動の充実
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもに屋外での活動を体験させる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/部活動合宿などを放射線量の低い地域で行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもを安全な場所で遊ばせる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/週末だけでも放射線量の低い地域ですごしたい
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援対象住民が移動する際の支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者の雇用確保に復興予算を使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災等緊急雇用対応事業に被災者以外も対象とする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/配分された予算を消費する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/各県に震災等緊急雇用対策事業の予算を配分する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/香川県内で就職する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援対象者の移動・帰還の選択の自由を保障する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難先の地方公共団体による支援を統一する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援法具体化の委員会を設置する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援法具体化委員に全国の被災者を加える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難者の声を聴く
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援法具体化委員会が全国の被災者と意見交換の場をもつ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援対象地域を年間放射線量1ミリシーベルト以上の地域に定める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/公共住宅入居の被災者に無償利用期間を延長する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/民間住宅の借り上げ・家賃補助を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災地と支援地域の移動費用の補助
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難している被災者の孤立感・疎外感を軽減する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先での被災者の生活支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先に置いて、同じ地域の被災者を同じ地域の住宅に入居できるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動による子どもの転校の支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/転校にかかわる手続きを簡略化する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/転校による精神的な支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/転校による学習面の支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/カウンセリングを実施する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/補習を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/転校によるいじめや差別が起きないようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/放射能に関する適切な知識を学校教育や地域への啓蒙・広報活動で行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/保育所や学童保育の優先枠を設ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/保育所や学童保育の利用料金の減免措置を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/自営業を移動先で営もうとする者への支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/自営業を営もうとするものに、債務負担の軽減措置を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/自営業を営もうとするものに、資金援助を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民票を移動していなくても移動先地域の行政サービスを受けられるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先と移動元の地方公共団体が情報を共有する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先地域に、相談・支援を一本化したワンストップ窓口を設置する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先での地域の情報を提供する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動元の地域の情報を提供する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先での被災者の公共交通料金無償化を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先での被災者の水光熱費の減免を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先地域の民間支援団体が支援できるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/住民票を移動しても移動元の地域の行政サービスを受けられるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/家族と離れて避難している子どもの家庭を支援する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/j家族と離れて避難している家族の再統合・維持を促進する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/家族と離れて避難している子どもの家庭に交通費の助成を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/家族と離れて避難している子どもの家庭に優先的に避難先での雇用をあっせんする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/家族と離れて避難している子どもの家庭に子育て支援サービスの利用を無条件で可能とするようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/支援対象地域外に移動した被災者を支援する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動して避難する被災者に被災ローン減免制度を適応する指針を定める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先でも支援地と同じ医療・検査が受けられるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先でも支援地と同じ心身の健康維持に関するサービスが受けられるようにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/一定の基準を定めて被災者の情報を民間団体に開示する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者の医療検査の記録を保存する方法を確立する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地へ帰還する場合の保障を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地への帰還費用を支給する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地へ帰還するための就労支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地へ帰還するための学習支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/近畿各県へ避難してきた被災者を支援する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者支援情報を提供する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/電話や面談による法律相談を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難者への聞き取り調査を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者を継続的に支援する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/母子家庭と同じサービスを受ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子育て中の母親を雇用する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもたちの将来の土台を作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/気仙沼に工房を作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/30人の雇用を生み出す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/第５回インターナショナル・マイクロファイナンス賞をピースジャムの佐藤賢さんに送る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/三陸復興トモダチ基金の助成を受ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京電力が損害賠償として１３億１５００万円富岡町に払う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/本来ならば得られるはずだった水道使用料やたばこ税などの減収分を東電が補償する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/避難先での学校・仮庁舎の建設費を東電が補償する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災津波で被害に遭った文化財の救援活動報告の展示会を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災資料の現状報告を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/これまでの文化財救助活動への全国の支援に感謝を表明する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/これからの文化財救援活動への支援を呼びかける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/津波のため塩に浸かった文化財の修復を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/災害研究を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/阪神大震災被災の経験を活かす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者が他地域に移り住んだ時に地域社会に起こる変化について研究する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興庁を被災地に移転する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/各自治体の現状に合わせた支援態勢を取る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/他省庁との調整機能を重視する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/移転の議論で復興を妨げない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/適切な手法で除染しているかどうかを調査する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/除染現場に環境省職員を配置し、監視を強化す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/除染に関する通報への省内対応について調査する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/現場責任者に聞き取り調査を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/手抜き除染の再発防止策をまとめる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/スピード感を持って手抜き除染再発防止に対応する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/手抜き除染による汚染に対する国民の不安をなくす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/双葉郡全体の復興
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/双葉郡の人材育成ビジョンを2013年5月に策定
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興に向けた育むべき人材像検討
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興教育検討
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/人材育成のロードマップ検討
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/毎月会合を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/コウナゴ漁の試験操業を実施する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/緊急雇用事業を受ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大雪りばぁねっと。の活動を休止する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大雪りばぁねっと。全従事者の解雇
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/山田町の雇用を確保する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大雪りばぁねっと。解雇者に雇用保険を給付する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/町に大雪りばぁねっと。停止に関する相談窓口を設ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/大雪りばぁねっと。解雇者に再就職への支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興支援予算を受けて事業を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/いわき・ときわ路夢街道キャンペーンを行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/茨城県への観光客を増やす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/茨城、福島両県の観光を盛り上げる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/JR東日本利用客を増やす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/地域の活性化
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/フクシマオーガニックコットンベイブを販売する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/オーガニックコットンプロジェクトに取り組む
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島から安全なものを届ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/和綿の有機栽培を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/和綿から人形を作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/フクシマオーガニックコットンベイブを買った人がタネを育てて綿をいわき市に送る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/遠隔地の消費者が福島のことを考える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ブックボーイを再興する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ブックボーイ駅前本店を再開する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/再建を迷っている人たちに希望を与える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもに被災の映像を見せない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/子どもに本を買う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/受験用の参考書を買う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/本が売れないなら店を再興しない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/生活圏に本屋が再開する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災・津波による行方不明者を捜索する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災・津波による全行方不明者の身元を確認し、遺族に渡す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/行方不明の家族の行方を知る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/DNA鑑定だけでなく、似顔絵なども活用する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/パトロールを行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/被災者に寄り添った活動を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/復興への希望を音楽に託す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/若山牧水の「みなかみ紀行」をオペラにする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東北を訪ね歩いた際の体験や、触れ合った被災者の思いを伝える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東北の自然を大切にする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東北の伝統を大切にする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「東北の人たちへ送る哀歌」を作曲
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京や新潟で「東北の人たちへ送る哀歌」を演奏する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/牧水の歌に曲を付ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/本店オフィスサービスセンターを福島県に移転する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/原発廃炉に向けた技術開発を行う国際チームを東京に設置する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/賠償についての説明が分かりづらい、対応が遅いとの批判に応える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故で失った消費者の信頼を回復する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/簡潔明瞭、スピード感を持って対応する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/自治会レベルの除染に放射線の知識がある東電社員延べ１０万人を参加させ、協力させる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/賠償や除染業務を本店から福島復興本社に全面移管する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故の賠償責任を果たす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故による汚染について除染を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/漂着した船を喜界島で使ってほしい
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/漂着した船を修理する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/モニュメントとして漂着した船を保存する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/震災の悲惨さを伝える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/喜界島島民の防災意識を高める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/漂着した船が島の人の役にたつ
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/「東日本大震災事業者再生支援機構」の事業再生プログラムの利用を増やす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/事業再生プログラムの認知度を上げる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/事業者に電話をし、事業再生プログラムの利用を促す
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/借金をしたくない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/説明会や相談会をひらき、事業再生プログラムについて説明する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/借金の一部返済猶予などの支援を受ける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/工場を再開させる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/市の担当者が、事業主に直接アプローチする
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/チリ地震の教訓を生かす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/阪神淡路大震災や、その後の様々な自然災害から得た教訓を生かし、防災教育を推進する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/模型を作り、津波の恐ろしさを伝える
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/宮古市内の小中学校の教員を招いて模型の津波実演をし、防災教育に役立てる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/宮古市内の小中学校で出張防災授業を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災の教訓を生かす
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/模型の作り方や実演方法を普及させる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/さらに多くの地域で実演を行い、防災教育に役立てる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ぼうさい甲子園に出場する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ぼうさい甲子園を開催する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/鳥追いの行事を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/えんずのわりの伝統を守る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/えんずのわりの行事を祝う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東松島市宮戸の月浜地区の被災者を元気づける
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/月浜の人たちが笑顔になる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/毎年鳥追いの子どもたちがやってくる
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/秋田市に認知症お年寄りのためののグループホームを作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/日本家屋の良さを生かしたグループホームを作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/一軒一軒大工の手作りによる個性がある古い日本家屋で、計約４０部屋をつなぐ新しいグループホームを作る
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災による液状化現象によって被災した家屋を移築する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/屋根部分をグループホームのために提供してもらう
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/家部分もグループホームのために提供する
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/液状化で被災した家を壊したくない
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/愛着のある家を秋田で生かしてほしい
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/東京、千葉、岩手からグループホームのための家を集める
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/仙台市が東日本大震災の津波で浸水した災害危険区域外の被災者への住宅再建支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国が東日本大震災の津波で浸水した災害危険区域外の被災者への住宅再建支援を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/仙台市の財源を仙台市全体のために有効に使う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/仙台市が独自に災害危険区域外の被災者への住宅再建支援金の増額や対象者の拡大を行う
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/国がもっと早い段階で災害危険区域外の被災者への支援を行う
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/c949e482-0988-708e-dc51-8cca6988901d
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/1b07c00d-b94f-5892-b99c-0d1d24e99345
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6c52c9d8-4423-cc1b-1a8f-870725274623
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/70597e3b-81eb-1c18-777e-0094d6a4dac6
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/a61b33b6-0abc-7932-ec57-b68a5c0e1599
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/88874f7b-fcfc-ce45-54c5-73c7d531beda
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/05234dba-1878-f0b0-7f0a-da11c10b0e5e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/b37af942-0e5d-f2fd-e046-004bbce38a2f
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/7f2ad0b0-c93a-ab7b-0a6b-cf5eedb2c492
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/83315197-32e1-b329-885b-7bebe3609b2d
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/4228cd0a-eced-a0c1-7fbf-d049edaf3c40
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/99cb077a-ee23-6e0f-1ac9-03d87628b013
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/632b4d80-4e16-e559-5cbf-11a78c626725
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6580e8e7-8f4f-c157-3c2c-8423da20b56e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/518f2ca1-3bad-9227-6935-497b0da5df52
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/b60f3fe2-aa56-2046-b682-0bd1aa42c58c
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/a6be6daf-06cc-6995-2e61-f69855c698a7
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8e7da5ab-9888-62c2-0a58-fbcb7cb87961
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/4fbfd70d-497b-0897-cba4-46f0c91f6f15
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/b0a688c0-a47f-80cf-0f2a-1dc218bf8b89
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e5a75768-f672-b6fa-51ed-5f9b01eac07e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/27ae8bb6-30bc-4549-6544-fc3e92fb08c5
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/13603f8d-b7eb-f1da-0ffa-bf319333ee2f
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6a797e34-0fba-fc38-0462-7cdaa9830ec5
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/458c4d3c-976f-adbf-789b-a65a585ce195
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/52c491b1-fa2b-49c7-c019-015fefdf7ff7
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e74bf11c-946f-f428-1c91-89b906119b19
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/20ccd5d9-9137-8590-5deb-3d3745a50971
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/a454c816-bf84-af45-92b0-8600c0e9fb87
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/3d016f5c-b0bd-72e8-5648-a15693a6e49a
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/TestiGoal
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/f9440963-72e0-57a8-c6b6-8ea70a02808a
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/caa4f588-f1a9-0c83-3254-2bc92eaa63b7
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/19a40583-3d41-08a4-0ef0-770e8cf11b39
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/2f283ae1-d53f-60c4-f60e-30e9a79c7d9b
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/8375090e-8cfc-5517-97df-a30125f9ed5c
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/1636ed46-622f-c210-7d4d-95c25950742a
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e83ba340-3e80-2caa-5f8c-9ef821b52b16
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/03095428-acbc-a9c9-0b91-9d386b8407f4
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/95a7d5a4-6dce-e27d-81c2-28e75b7ea3da
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/981bf860-031b-d1f8-85fe-512f8d7d07de
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/702f8563-8148-d52f-9342-112a79d7252e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/7e4abe7d-b6da-3316-6da7-8979e25ea046
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/fee41fbc-53c9-7c8d-3bcf-edcaabed2530
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d3d3abe0-011d-2a02-9117-8d363bf2f064
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/f12cd66b-e009-3d98-51fd-1ee242f83e22
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/2007a49a-d900-9b3c-02e2-3e77ace44fd1
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/82f0ecc3-f9dc-d926-3362-1e6406d9f990
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/a78e5dde-b89d-e320-3eec-6d3ec76e5f4b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/aed785ee-d155-8544-2d28-a6e01153c3fc
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/952855ea-e71a-c684-4e17-6c8521df6c43
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/bbd4dbef-23ff-e600-2ffc-a1df4f89de8a
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/dbc980ad-8264-4981-7946-847895711f50
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/bebf13bb-d80a-6e5f-c8a4-3b1d8dd3630a
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/78076690-d7e6-3074-5914-2befd1ddf84f
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/b9505940-6768-743a-5c35-3c1b6eca663c
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/ss
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8b95f9a4-4608-98a0-9a22-4e2d48b29197
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e2b44c68-3bdc-6e73-b922-a3ecc721aefe
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e78170c7-93b9-0b3e-b5b7-12cdf7cf3a74
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e0c50dc8-1952-00b2-07e8-fde2823d6a4d
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e7df6538-89a7-630f-f777-a3cdfe3ca21e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/cbd5033a-4070-9abd-455e-2841a88836c8
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/80c92c47-6649-2c68-6eb4-6335e1941c75
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/55fb6e4e-2806-e75c-0df2-8383bf604b22
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/0a32434a-039a-1a71-3922-b0337e6defbd
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/74c34d2a-7c18-05b5-855c-343cabf00ef8
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/74ed5a5c-f0ce-9cb9-60ae-254a2a7d1572
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/f253af37-fd56-12e8-6f51-8da778a3ea4a
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/4f0d65e8-4e08-c925-e7cc-9901606a2662
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/0fec96ca-e8b2-2f33-a79d-a0d4b89fe3f3
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/1c1bc526-d2ca-f071-6faf-0736c2c19425
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/628142c2-e320-41bd-1d6b-0ec0d34b14de
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/c90ac984-0403-86a9-d765-be72896fccdd
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/3fa2e238-d1c4-f354-d335-b187379816b3
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/b7364083-0748-f622-bd63-f07892e783bf
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/45b60035-2813-1b08-6f5c-6b8ea8a42a00
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/7c3de4ee-b7c0-8dbc-67ca-6aedb0abe9c3
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6ec1716d-3e0b-7944-ed9f-18fc8be4e80e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8ea3977d-f4d9-bedd-9cb8-902ea410b382
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8377f620-1bb5-f735-93f8-fd4b0bfd6dbb
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/225d06da-182f-ed5a-55b6-6762d8d1a4e4
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/672df245-e0d8-442e-9c4d-aa452f0b3981
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/ce43c0a3-1d84-a780-a36e-2390085f6b38
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/5b13856c-7ab6-de2a-cb13-85cabdb9cbbd
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/2a89916f-99ca-1df6-c546-9bbedd3ed152
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/c77ac815-3298-2052-46e3-647c5c98f5ef
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/Testi
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/eee
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/test
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/testi
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/Janna
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/Teemuntesti
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/teemuTes
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/Jess
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/TestGoal
./calc_similarity_fixed.pl http://data.open-opinion.org/socia/data/Goal/TopLevelGoal
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/0bcb8852-e85d-ad80-0477-658c44d4636d
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/60f4d49f-63ae-7376-b4e8-f55853df4baf
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/3d4be51d-4fc5-7178-586e-e97d6a2e2868
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/0fc2fc70-8262-695d-352e-904d51539364
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/1d71e38a-fb0a-7c43-b690-faed47e21a75
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/1d71e38a-fb0a-7c43-6666-faed47e21a75
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/da4756bf-ec43-78c0-6208-44dfbafb0951
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/4ba4cd34-cf5c-5fb9-9416-9b7d1af99c93
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8f7f21ec-2f0e-9c12-d1a3-5cd8f2c97671
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8f48ed37-4369-40de-349f-f7a68dfbfecd
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/ee6dd7a5-b3a1-8b26-d1ca-ea59fb6648b2
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d5f131e8-edcf-31c1-bb75-9d228875d326
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/c0270aa7-b9b9-9079-18a8-53a7298e9786
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/edf8efb7-d052-47f0-d235-a17bc605cc42
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d7beebc1-c885-4d49-1480-6be506cd21b3
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/c98e4be8-dd93-801e-8f7a-8f912144c8a9
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/299ebd03-ece6-6140-1e65-13a2e9f2d2a3
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/3366368b-4601-0dd4-1cda-eb8d269109f2
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/29665768-e5a2-6c71-5bff-968d66da5895
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/081f3584-685d-3703-05f2-4a5a3152d05a
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/436336115205697536
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6f16376b-2aea-381e-59f7-911d828f4cbb
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/0793c3cb-d70d-eced-bb8f-ff5737c1f481
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8f4b2ba1-da0d-e57f-c2f0-81de71cc9681
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d78271aa-ec20-5e9a-ba10-a2776dd732f2
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/4c0836a2-b80f-0634-0396-3b527e91d54e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/47888cd8-157f-1a54-bd12-9a687f5fd49c
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/4683f03b-f2ba-a666-0ea8-0cae6193162b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/48b01d68-93c3-2f04-f209-ab629a3eb2af
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/ec3d10bd-d51f-7ab9-5f76-03a28cb18ddb
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/fd26cb03-9545-3538-4d14-b31ccc0ae722
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/37ac68df-b293-a0e1-2611-d3627ee8c841
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/47102e37-d7a8-6604-fb5b-8f8c813bdede
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/69e8c946-d587-d772-8632-2ba4d1574239
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/c5b3d5c3-49d0-97be-7e34-1c57ef4e9675
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6c839ec7-e6d2-49b6-b5e1-218416ab3702
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/45c3b746-98d6-c0a9-61ab-2efcf695d905
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/88fd4e67-2c3c-82c5-aa23-3020cea69279
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6f91b4b3-2d2d-4e86-5e26-b3112ab14078
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/11b3d611-c756-fff6-0f67-851fadb10890
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/1bda3a9c-aabf-6594-e9ed-966f3111c5f1
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/4f782a31-e56e-98c1-bd0a-4d1632340a4b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/820bb2f4-f2f7-908e-8576-3135064b0b2f
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/b2c9b1e1-6d42-7013-4171-baafe9660a03
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/1533739a-f00a-082d-8f9b-8fc9d05d620a
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/43bdc87b-13d5-6158-fca6-6f6218ba7ccb
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/5fbc54c1-a8af-d568-b85f-a92107f0fcd0
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/cd0347ec-aaad-9aad-a7d8-c1ec857b1b20
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d42886d3-2094-b38a-6b50-d18e5097e7bc
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/192264df-c6aa-27f2-a1f4-3b5f648ccf72
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/a0f21415-c5b3-685d-538b-4d799d761158
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/dfb7c5ef-f0cc-36a3-0837-378d656d4341
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/fc6db6c8-151a-a388-93d0-062f547e5e41
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/af9058e1-649c-779a-7858-fab69325be42
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/46d5e3a1-abff-272d-3ba2-263f550e7be9
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/ab72b65c-9a37-1b4f-01de-075abf9f364c
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/80cad402-2927-38d3-9b82-9bf3aa86190a
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/ea651076-ded7-78bf-4c70-b29598f46a44
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8d8061e9-10fe-03b7-1c3b-fe8e7d1556f5
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/11b8e3c6-23bf-dbe8-426e-f88c1e09baa6
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/f3259d45-dd59-ffbf-16b7-bbabeb714eb2
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/3cdc68eb-e2b5-c467-4be4-b2f24b52cee7
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/66821ff1-7f23-bc03-800d-b0aa2b5eff6d
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d1d77463-1df5-a901-dee9-d1f6b79cf00e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/1e953e85-30dc-e65b-d948-1a0f0fbdda22
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/4748ddb4-c42b-540d-5ef4-36849a33fdd8
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/9a81f151-461a-6fea-b627-8d00d8681b0b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8f49c006-c263-cdc3-3ab6-51ba81898703
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/93c1180e-760e-1ca4-a0ee-bfe003d762fb
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/f107dbf6-aa58-7b26-4cc2-a228c556c56b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/cde16363-cf89-ebc6-b9e3-13eaf30fb11b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d7a8f4f5-2e20-a49c-6baf-7fece277ec62
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8b99a16d-47f0-1e59-c5e0-afe32d7e2a40
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8208064f-4d81-57e2-88de-89b6e30d0954
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/61b0a824-8899-e609-385b-b3ed895d0c82
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/c69cbec8-6750-26d3-c902-3e4a228dfc6b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e32934f9-9c67-8caa-8f44-60ee869dbc72
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/dcd0e314-7972-79be-914d-c828f2b0c96b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/3a98447e-d9c7-560e-20cf-3cfdaf68cd93
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/ba85e3d2-f8ea-ce36-a80c-ae61d2795468
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/abf6d300-7af8-dde4-22ee-7060fe206bf4
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/54ef223b-4959-316e-b087-e1f00e69d9f7
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/c1af18aa-ba97-2cf0-4e0c-e89cab093823
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/895813d9-163d-75a9-6fc6-843ccf24a7fb
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/5c430e28-4783-6d4d-d4d4-1c5ddd998a30
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/464991a8-4a6a-f207-47f6-99b82858f438
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6e4f837f-6382-e2a3-cfe7-0f57d1b6108e
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/2fd601cb-8b5a-7f4f-d740-a0e97d2eedf1
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/50e98d73-4fd9-a536-29bc-16a033cde162
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d0bd197c-4c5f-046e-0f70-c6ff6a19f644
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/5cff7beb-faf9-545d-a489-2a24fdd5fdb4
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d9de7f26-a24d-1290-cc9b-bd3cdb41b942
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e1362841-453a-57e7-44af-6dffe08e0058
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/41e4a045-ceea-71fb-ccfc-e39872ae387b
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/437034658736250880
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/437030690178093056
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/31e996bf-a54c-89b3-cd76-fa1a4f73cfc7
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/8d63d930-deeb-d93a-428a-7f09f70f2f47
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/438474540121718785
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/6f401da7-d62a-9746-b2f1-4e807df4ac97
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/1c94e314-de8d-5efc-8652-8b1ec5d68158
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/d19e6cd9-43fe-07ec-63b1-460fefe3576a
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/e24551c1-38d9-e809-ba44-5a5620897df0
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/7ff98144-80a0-6771-3727-33067fe47f9d
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/531d7f3a-9365-02d7-e3bc-af07736553da
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/5ecc8dc7-18c6-8c93-5a12-d07d62e049a3
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/175e55ef-fe7a-f997-240a-cb6782051e68
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/3b9a9e89-3676-1dd9-460a-41fae1e1d2bc
./calc_similarity_fixed.pl http://collab.open-opinion.org/resource/Goal/436696293105102848

