#!/bin/bash
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/震災復興
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/放射能除染
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/住民の帰還
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/生活の再建
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/復興予算の大幅見直し
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島県内に100万kW級の石炭ガス化複合発電（IGCC）の新設
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島県内での1万kW級のメガソーラー発電所を複数箇所に展開
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島県内で最大2000人規模の雇用創出
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島原発から東京への送電線の利用
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/震災復興財源確保
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/震災がれき処理
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災と東京電力福島第一原発事故からの再生と次代へつなぐ共同の実践
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島県内ＪＡを合併再編する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/衆議院選挙立候補予定者が復興への道筋を示す
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/避難生活の基盤整備
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/震災復興祈念八重桜植樹祭を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災の被災者のための集会所「みんなの家」を作る
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/被災道路の整備を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/南三陸町の復興
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/南相馬市の復興
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/震災で激減した乗客を呼び戻す
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/岩手県の復興
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/陸前高田市の復興
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/「不良建設業者」を排除する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/復興予算の配分を被災地を最優先にする
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災の復旧工事を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島第１原発事故の避難区域見直しを行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/避難区域の解除
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/東北に観光客を誘致する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島の特産品のすばらしさをＰＲする
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/避難住民の帰還
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/閖上の復興計画の遂行
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/再生を目指す複数の中小企業を支援する「グループ補助金」の充実
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/雇用のミスマッチの解消
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/東京電力福島第1原発事故に対応する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/村民の帰村
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/震災復興事業を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/仙台市の災害危険区域外の津波浸水地域住宅の再建
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災の津波で浸水した災害危険区域外の被災者への住宅再建支援を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/特殊ビデオカメラを除染作業で利用する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/「指定廃棄物」最終処分場を高萩市上君田の国有林に造る
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/中間貯蔵施設を建設する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/早期除染
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/TPP参加
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/衆院解散
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/政権の維持
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/大熊町に戻る
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/住民帰還の作業拠点となる宿泊施設の設置
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/町民の絆を保つ
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/帰還可能地域の住民に対する意識調査を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/教育環境の整備
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/被災地の学生向けにインターネット上で教育や就職などの支援を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/農業の復興
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島ブランドの信頼回復
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/被災した農家支援
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/野生動物による農業被害を阻止する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/営農再開
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/漁業の復興
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/ノルウェー型の漁業・水産業の資源管理を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/底引き網漁の漁場を確保する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/本格操業
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/コウナゴ漁の本格操業
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/雇用の確保
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/NPO法人大雪りばぁねっと。活動停止に対する対策を講じる
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/広野工場の求人
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/本店オフィスサービスセンター移転により雇用を創出する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/収入の確保
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/消費税増税前に再建する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/被災者の就労支援
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/防災集団移転先の宅地を決める
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/生活の早期再建
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/自営業者への支援を行う
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/被災した零細事業者の二重ローン問題を解消する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/２０１１、１２年度予算のうち、１１府省の３５事業１６８億円分の執行を停止する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/１３年度以降は被災地の復興と被災者の生活再建のために限る
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/平成２５年度復興予算編成
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島原発事故責任追及と補償
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/福島原発事故第２次集団告訴の立件
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/公害犯罪処罰法違反の適用
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/水素爆発で原子炉建屋を損壊させた業務上過失激発物破裂の適用
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/「津波や過酷事故の対策を怠り事故を招き、放射性物質を排出させた」などとする業務上過失致死傷の適用
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/受刑者の就労支援への復興支援予算の支出
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/減災に向けた広報・啓発への復興支援予算の支出
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/事業仕分
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/JT株を2012年度内までに売却
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/全国の国家公務員宿舎の使用料（賃料）を平均5割引き上げる
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/売却益を東日本大震災の復興財源に充てる
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/2012年3月までに震災がれきの53％を処理する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/Ｍｉｎｄ－１日本プロジェクトの継続
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/岩手県陸前高田市へと所属選手、クラブスタッフを派遣し現地でサッカー教室を開催
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/陸前高田市から被災児童やその保護者などを招待した川崎修学旅行の実行
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/Ｍｉｎｄ－１ニッポンプロジェクトの街頭募金活動
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/ぎんなんを販売する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/震災復興支援金を送る
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/生活再建支援金を被災者に支給する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/除染対策
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/再生可能エネルギーの利活用
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/きめ細かい放射性物質検査の実施
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/浮体式洋上風力発電所を建設する
./calc_similarity.pl http://data.open-opinion.org/socia/data/Goal/環太平洋連携協定（ＴＰＰ）交渉参加反対







