dictionaries = {
        en: {
            "GoalShare": "GoalShare",
            "Slogan": "Share public goals → Find collaborators",
            "Nav_Issues": "Issues",
            "Nav_Goals": "Goals",
            "Nav_Maps": "Maps",
            "Nav_People": "People",
            "Nav_Chronology": "Chronology",
            "Goal": "Goal",
            "Subgoal": "Subgoal",
            "ParentGoal": "Parent goal",
            "Title": "Title",
            "Description": "Description",
            "Reference": "Reference",
            "Socia_Issue": "Socia:Issue",
            "Socia_Goal": "Socia:Goal",
            "StartDate": "Start date",
            "EndDate": "End date",
            "CreatedDate": "Created date",
            "DesiredDate": "Desired date",
            "CreatedBy": "Created by",
            "Keyword": "keyword",
            "Status": "Status",
            "Status_NotStarted":"Not started",
            "Status_Aborted": "Aborted",
            "Status_InProgress":"In progress",
            "Status_Completed": "Completed",
            "Status_Unknown": "Unknown",
            "ResultLimit": "Result limit",
            "Subgoals": "SubGoals",
            "Subgoals_HeaderText":"Subgoals of the current goal",
            "Name":"Name",
            "Calendar": "Calendar",
            "Act_CreateGoal": "Create new goal",
            "Act_Search": "Search",
            "Act_AddSubgoal": "Add subgoal",
            "Act_listSubgoals": "Subgoals",
            "Act_Register": "Register",
            "Act_SignUp": "Sign up",
            "Act_SignUpSignIn": "Sign in / Sign up",
            "Act_Apply": "Apply",
            "Act_Cancel": "Cancel",
            "Err_NoResults": "No results",
            "Err_Error": "Error",
            "Err_ConnectionLost": "The connection has been lost",
            "T_MultiSelect_None": "None",
            "T_MultiSelect_All": "All",
            "T_MultiSelect_SelectedText":"# Selected",
            "X_DateFormat": "yyyy-MM-dd",
            "X_DateFormatJQ": "yy-mm-dd",
            "X_FullDateFormat": "yyyy-MM-ddThh:mm:ss",
            "CompletedDate":"Completed date",
            "CompetedDate":"Completed date",
            "Act_GetInfo":"Details",
            "SubgoalsHeader": "Subgoals",
            "RequiredDate": "Required date",
            "Act_FindSimilarGoals": "Similar goals",
            "Act_FindCollaborators": "Collaborators",
            "Status_Icon_NotStarted":"img/png/32x32/comments.png",
            "Status_Icon_Aborted": "img/png/32x32/warning.png",
            "Status_Icon_InProgress":"img/png/32x32/process.png",
            "Status_Icon_Completed": "img/png/32x32/accept.png",
            "GoalsListHeader": "Public goals",
            "WisherListHeader":"Goal wishers",
            "ParticipantListHeader":"participants",
            "Act_AddAsCollaborator": "participate",
            "Participant_AddedMessage": "Participant added",
            "Act_CreateIssue":"Create new issue",
            "LinkToGoal":"Link to goal",
            "CreateGoal":"Create goal",
            "IssueListHeader":"Issues",
            "IssueEditHeader":"Issue",
            "Act_AddIssue":"Add Issue",
            "Act_AddAsGoal":"Add goal",
            "AddReference":"Add",
            "Remove":"Remove",
            "Act_NextPage":"Next",
            "Act_PrevPage":"Prev",
            "IssueSollution":"Solution",
            "Wisher": "Wisher",
            "AskLoginMessage":"Please login with facebook!",
            "GoalDetailHeader":"Details",
            "IssueDetailHeader":"Details",
            "Participants":"Participants",
            "RegionalLocation":"Location",
            "Act_Create":"Create",
            "Anonymous": "Anonymous",
            "Delete":"Delete",
            "DeleteConfirm":"Delete",
            "Act_Complete": "Ok",
            "Related": "Related",
            "LogIn": "Please log in",
            "NoPermissionToDelete": "No permission to delete",
            "NoPermissionToEdit": "No permission to edit",
            "Nav_Help":"Help",
            "HelpTitle": "Faq",
            "HelpLinkMessage": "Help",
            "HelpHeader": "If you are having any questions about the GoalShare, please contact us by  goalshare@open-opinion.org.",
            "FAQHeader":"Here are answers to some common questions",
            "FAQ_EnableCookiesTitle": "There is a problem with the Facebook login.",
            "FAQ_EnableCookiesText": "Please make sure that cookies, including third-party cookies, are enabled in the browser.",
            "DirectLink":"Link to the goal",
            "Act_OK": "Ok",
            "Act_FocusOnGoal": "Focus on goal",
            "GoalTree_Instructions" : "Mouse wheel or double click zooms the tree view",
            "Tags": "Tags",
            "AddTag":"Add",
            "CC":"<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by/4.0/88x31.png\" /></a><br />The data inputted to GoalShare system is licensed under <a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">Creative Commons Attribution 4.0 International License</a>.",
            "CCSmall":"<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">The data inputted to GoalShare system is licensed under <a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">Creative Commons Attribution 4.0 International License</a>.",
            "SOMEURI":"User's url",
            "addUserByURI":"Add user",
            "addUser":"Add user",
            "Add":"Add",
	    
	    "IssueGathering": "Issue gathering",
	    "IssueSelection": "Issue selection",
	    "ProblemDefinition": "Problem definition",
	    "SolutionForming": "Goal forming",
	    "GoalSplitting": "Goal splitting",
	    "ConflictRecognition": "Conflict recognition",
	    "ConflictResolution": "Conflict resolution",
	    "Voting": "Voting",
	    
	    "DefaultTopic": "Topic",
	    "DefaultTopicDescription": "Description",
	    "DefaultNoteTitle": "Note",
	    "DefaultNoteDescription": "Description",
	    
	    
	    "AddNote": "Add note",
	    "QuickSave": "Quick save",
	    "QuickLoad": "Quick load",
	    "LoadCompare": "Load compare",
	    "ClearTable": "Clear",
	    "SaveToGS": "Save",
	    
	    "Merge": "Merge",
	    
	    "Conflict": "Conflict",
	    "Connect": "Connect",
	    "DeleteHeader": "Delete",
	    "Replace": "Replace",
	    "CreateNew": "Create new",
	    "SaveHeader": "Save?",
	    "SaveDescription": "Save?",
	    "LeftTree": "Left tree",
	    "RightTree": "Right tree",
	    
	    "Action": "Action",
	    "Save":"Save",
	    "Load": "Load",
	    "Cancel": "Cancel",
            "Last": "Last"
        },
        ja: {
            "GoalShare": "ゴオルシェア(仮)",
            "Slogan": "目標を公開 →「一緒にやろうよ」を探す",
            "Nav_Issues_old": "解決してほしい",
            "Nav_Issues_short_old": "課題",
            "Nav_Issues": "解決してほしいこと",
            "Nav_Issues_short": "課題",
            "Nav_Goals": "目指してること",
            "Nav_Goals_short": "目標",
            "Nav_Maps": "地図",
            "Nav_People": "人々",
            "Nav_Chronology": "年表",
            "Goal": "目標",
            "Subgoal": "部分目標",
            "ParentGoal": "上位目標",
            "Title": "タイトル",
            "Description": "詳細",
            "Reference": "引用記事",
            "Socia_Issue": "Socia:Issue",
            "Socia_Goal": "Socia:Goal",
            "StartDate": "開始日",
            "EndDate": "終了日",
            "CreatedDate": "作成日",
            "DesiredDate": "達成したい日",
            "RequiredDate": "達成締切日",
            "CreatedBy": "作成者",
            "Keyword": "キーワード",
            "Status": "達成状態",
            "Status_NotStarted":"未着手",
            "Status_Aborted": "中止",
            "Status_InProgress":"遂行中",
            "Status_Completed": "完了",
            "Status_Unknown": "不明",
            "ResultLimit": "検索表示件数",
            "Subgoals": "部分目標",
            "Subgoals_HeaderText":"具体的な部分目標",
            "Name":"名称",
            "Calendar": "カレンダー",
            "Act_CreateGoal": "新しい目標を作る",
            "Act_Search": "検索",
            "Act_AddSubgoal": "部分目標を追加",
            "Act_listSubgoals": "部分目標を表示",
            "Act_Register": "登録",
            "Act_SignUp": "ユーザ登録",
            "Act_SignUpSignIn": "ログイン / ユーザ登録",
            "Act_Apply": "適用",
            "Act_Cancel": "取り消し",
            "Err_NoResults": "検索結果なし",
            "Err_Error": "エラー",
            "Err_ConnectionLost": "コネクションが切れました",
            "T_MultiSelect_None": "なし",
            "T_MultiSelect_All": "全て",
            "T_MultiSelect_SelectedText":"#",
            "X_DateFormat": "yyyy-MM-dd",
            "X_DateFormatJQ": "yy-mm-dd",
            "X_FullDateFormat": "yyyy-MM-ddThh:mm:ss",
            "Status_Icon_NotStarted":"img/png/32x32/comments.png",
            "Status_Icon_Aborted": "img/png/32x32/warning.png",
            "Status_Icon_InProgress":"img/png/32x32/process.png",
            "Status_Icon_Completed": "img/png/32x32/accept.png",
            "CompletedDate":"達成した日",
            "CompetedDate":"達成した日",
            "Act_GetInfo":"詳細を見る",
            "SubgoalsHeader": "部分目標",
            "Act_FindSimilarGoals": "似た目標を探す",
            "Act_FindCollaborators": "協力者を探す",
            "GoalsListHeader": "目標のリスト",
            "WisherListHeader":"目標への賛同者",
            "ParticipantListHeader":"目標への参加者",
            "Act_AddAsCollaborator": "参加してみる",
            "Participant_AddedMessage": "参加者として追加されました",
            "Act_CreateIssue":"新しい課題を作る",
            "LinkToGoal":"この課題を解決する目標とつなげる",
            "CreateGoal":"新しい目標を作る",
            "IssueListHeader":"課題",
            "IssueEditHeader":"課題",
            "Act_AddIssue":"課題を追加",
            "Act_AddAsGoal":"目標を作る",
            "AddReference":"引用を追加",
            "Act_NextPage":"次へ",
            "Act_PrevPage":"前へ",
            "GoalDetailHeader":"詳細",
            "IssueDetailHeader":"詳細",
            "Participants":"参加者",
            "AskLoginMessage":"Facebookアカウントをお持ちの場合は，そのアカウントでログインして下さい",
            "RegionalLocation":"場所",
            "Act_Create":"作成",
            "Wisher": "目指している人",
            "GoalTree": "目標の階層構造",
            "Nav_GoalTree": "目標の階層構造",
            "Anonymous": "匿名",
            "Act_Delete":"削除",
            "DeleteConfirm":"削除しますか？",
            "Ok":"はい",
            "Cancel":"取り消し",
            "Act_Edit":"編集",
            "Act_Complete": "完了",
            "Menu":"メニュー",
            "NotUsed":"まだ使えません",
            "ClearFilters":"クリア",
            "AdditionalFilters_ToolTip":"詳細検索を出す...",
            "Location":"場所",
            "Related": "関連情報",
            "LogIn": "ログインして下さい",
            "NoPermissionToDelete": "削除権限がありません",
            "NoPermissionToEdit": "編集権限がありません",
            "Nav_Help":"ヘルプ",
            "HelpTitle": "よくある質問（FAQ）",
            "HelpLinkMessage": "ヘルプ",
            "HelpHeader": "ゴオルシェアについてご意見・ご質問がありましたら，どうぞgoalshare@www.open-opinion.orgまでお報せ下さい",
            "FAQHeader":"よくある質問（FAQ）に対する回答です",
            "FAQ_EnableCookiesTitle": "Facebookログインに失敗します",
            "FAQ_EnableCookiesText": "ブラウザの設定で「サードパーティのCookie」が無効になっているとログインできませんので，その場合は有効にして下さい",
            "DirectLink":"目標へリンク",
            "Act_OK": "了解",
            "Tags": "タグ",
            "AddTag":"タグを追加",
            "CC": "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by/4.0/88x31.png\" /></a><br />入力された目標や課題のデータは、<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">CC-BYライセンス</a>で公開されます．CC-BYとは、引用元を明記すれば許諾なしで再利用できるライセンスです。",
            "CCSmall": "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">入力された目標や課題のデータは、<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">CC-BYライセンス</a>で公開されます．CC-BYとは、引用元を明記すれば許諾なしで再利用できるライセンスです。",
            "SOMEURI":"Url",
            "addUserByURI":"URIを指定してユーザ追加",
            "addUser":"ユーザ追加",
            "Add":"追加",
	    
	    "IssueGathering": "",
	    "IssueSelection": "",
	    "ProblemDefinition": "",
	    "SolutionForming": "",
	    "GoalSplitting": "",
	    "ConflictRecognition": "",
	    "ConflictResolution": "",
	    "Voting": "",
	    
	    "DefaultTopic": "",
	    "DefaultTopicDescription": "",
	    "DefaultNoteTitle": "",
	    "DefaultNoteDescription": "",
	    
	    
	    "AddNote": "",
	    "QuickSave": "",
	    "QuickLoad": "",
	    "LoadCompare": "",
	    "ClearTable": "",
	    "SaveToGS": "",
	    
	    "Merge": "",
	    "Conflict": "",
	    "Connect": "",
	    "DeleteHeader": "",
	    "Delete": "",
	    "Action": "",
	    "Save":"",
	    "Load":"",
            "Last": "最後へ"
        }
    };
var locale = {
    // Default set
    
    currentDictionary: dictionaries.en,
    currentLanguage: "en",
    setLanguage: function(lang){
            
            if( lang != locale.currentLanguage ){
                    locale.currentLanguage = lang;
                    locale.currentDictionary = dictionaries[lang];
                    
            }else{
                    //console.log("Lang diff:" + Locale.currentLanguage + " " + lang);
            }
	    locale.localize();
    },
    init: function(){
	// Default en
	this.currentDictionary = dictionaries.en;
		
    },
    localize: function(){
	$("[data-localize]").localize("locale", { language: this.currentLanguage,
				      pathPrefix: "https://radish.ics.nitech.ac.jp/gsneg/apps/gsneg",
				      callback: function(data, cb){
					console.log(data);
					console.log(this);
					cb(data);
				      }
				      });
	$("[data-localize-title]").localize("locale", { language: locale.currentLanguage,
					    pathPrefix: "https://radish.ics.nitech.ac.jp/gsneg/apps/gsneg",
					    callback: function(data){
						    console.log(this);
						    console.log( data );
						    //data.title = 
						}});
	//gsneg.literals.DEFAULT_TITLE = locale.currentDictionary.DefaultNoteTitle;
	//gsneg.literals.DEFAULT_DESC = locale.currentDictionary.DefaultNoteDescription;
	
    }
};

(function(){
    locale.init();
})();