#!/bin/bash
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東通原発の再稼働
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/養殖魚を活用して被災地を応援する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/魚介類の全量放射能検査できる機械の開発
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/相馬のノリ養殖の復活
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/放射性物質の自主検査に要した費用を東京電力に損害賠償請求する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/安全な水産資源を消費者に届ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/漁業再興のために番小屋を建設する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/漁業者の復興がかなうまで支援を続ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島に廃炉の国際拠点
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/「ＩＡＥＡ緊急時対応能力研修センター」を福島県内に設置
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/住民の健康管理
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/放射線災害医療の作業グループを設置
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/原子力対策で日本が主導的役割を果たす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/IAEAの知識を福島に生かす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/原発をめぐる情報の透明性強化
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/原発の新規導入国の安全性確保
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/アジア太平洋地域での原子力事故に備える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/会津若松市に仮園舎を置く大熊幼稚園に絵本１５０冊寄贈する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/読み聞かせに力を入れる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災地を支援する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/「復興なみえ町十日市祭」を開催する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/浪江町の風物詩を再現する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/浪江町内各地の神楽や田植踊りなどの伝統を維持する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/相馬焼の伝統を保つ
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/全国に避難した浪江町の小学生が祭りに参加する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/会場から同市小沢工業団地に開設された大堀相馬焼の工房行きのバスを運行する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/法テラスふたばを広野町に設置する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/いわき市などに避難する被災者が利用する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動相談車を配備する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/原子力損害賠償紛争解決センターへの申し立て依頼を受け付ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災者に賠償についての知識を伝える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/刑事事件以外の法律相談を受け付ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援法の具体的な施策を充実させる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援対象地域を福島県全域にする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/国が支援法について周知徹底を図る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/国が支援法について対象住民に対する意識調査を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/国が子ども・被災者支援法専門窓口を設置する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援対象住民が移動しても支援を受けられるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもを連れて県外に避難する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/母子・父子で避難している被災者への支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもを被爆から守る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島県民を分断しない
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/安定した支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/風評被害から県民を守る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島への転入者を保護する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島の復興
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/地域の生活と環境を回復する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/これから生まれてくる被災者の子どもを守る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/法的に求償が困難あるいは不可能な損害に対する支援は具体的施策に盛り込まない
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/除染に関する知識・技術に関する説明や研修を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/「除染の日」制度を作る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/全国的な支援を得る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/放射能に対する正確な知識を国民に啓発する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/医療や商店の整った地域に帰還する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/住民が帰還した地域に出店・開業する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/帰還可能地域での事業再開や新規進出に対する資金援助を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/放射線量が上昇した地域で生活を継続する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/住民それぞれが適切な放射線防護を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/空間線量等の情報公開を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/精密な線量調査を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/内部被ばくを回避する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/自己の外部被ばくの状況を正しく把握する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/ガイガーカウンターやガラスバッジを配布する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/ガイガーカウンターの無料校正機関を各地に広く設置する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/ガラスバッジを改良する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/飲食品の放射性物質含有量検査等の情報提供を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/全国の産品の放射性物質含有量検査結果を誰でも検索できるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島県だけでなく、全国の産品の放射性物質含有量検査の全量・全袋検査を実施する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/放射性物質含有量が、消費者が購入する場面で簡単に確認できるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援対象地域内に子どものための屋内施設を確保する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもの発育権を保障する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/総合子ども施設を新設する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/民間の体育館や遊園地を子ども・被災者支援施設として一般無料開放できるよう助成する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/週末避難の支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/週末避難のための交通費の負担軽減
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/国営・公営施設の利用負担軽減
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/保養地に置いて外部被ばく検査を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもの親に保養休暇制度を創設する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/放射線量の低い地域での体験活動の充実
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもに屋外での活動を体験させる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/部活動合宿などを放射線量の低い地域で行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもを安全な場所で遊ばせる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/週末だけでも放射線量の低い地域ですごしたい
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援対象住民が移動する際の支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災者の雇用確保に復興予算を使う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/震災等緊急雇用対応事業に被災者以外も対象とする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/配分された予算を消費する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/各県に震災等緊急雇用対策事業の予算を配分する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/香川県内で就職する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援対象者の移動・帰還の選択の自由を保障する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/避難先の地方公共団体による支援を統一する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援法具体化の委員会を設置する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援法具体化委員に全国の被災者を加える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/避難者の声を聴く
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援法具体化委員会が全国の被災者と意見交換の場をもつ
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援対象地域を年間放射線量1ミリシーベルト以上の地域に定める
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/公共住宅入居の被災者に無償利用期間を延長する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/民間住宅の借り上げ・家賃補助を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災地と支援地域の移動費用の補助
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/避難している被災者の孤立感・疎外感を軽減する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先での被災者の生活支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先に置いて、同じ地域の被災者を同じ地域の住宅に入居できるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動による子どもの転校の支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/転校にかかわる手続きを簡略化する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/転校による精神的な支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/転校による学習面の支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/カウンセリングを実施する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/補習を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/転校によるいじめや差別が起きないようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/放射能に関する適切な知識を学校教育や地域への啓蒙・広報活動で行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/保育所や学童保育の優先枠を設ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/保育所や学童保育の利用料金の減免措置を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/自営業を移動先で営もうとする者への支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/自営業を営もうとするものに、債務負担の軽減措置を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/自営業を営もうとするものに、資金援助を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/住民票を移動していなくても移動先地域の行政サービスを受けられるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先と移動元の地方公共団体が情報を共有する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先地域に、相談・支援を一本化したワンストップ窓口を設置する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先での地域の情報を提供する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動元の地域の情報を提供する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先での被災者の公共交通料金無償化を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先での被災者の水光熱費の減免を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先地域の民間支援団体が支援できるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/住民票を移動しても移動元の地域の行政サービスを受けられるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/家族と離れて避難している子どもの家庭を支援する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/j家族と離れて避難している家族の再統合・維持を促進する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/家族と離れて避難している子どもの家庭に交通費の助成を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/家族と離れて避難している子どもの家庭に優先的に避難先での雇用をあっせんする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/家族と離れて避難している子どもの家庭に子育て支援サービスの利用を無条件で可能とするようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/支援対象地域外に移動した被災者を支援する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動して避難する被災者に被災ローン減免制度を適応する指針を定める
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先でも支援地と同じ医療・検査が受けられるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先でも支援地と同じ心身の健康維持に関するサービスが受けられるようにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/一定の基準を定めて被災者の情報を民間団体に開示する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災者の医療検査の記録を保存する方法を確立する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地へ帰還する場合の保障を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地への帰還費用を支給する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地へ帰還するための就労支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移動先から支援地へ帰還するための学習支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/近畿各県へ避難してきた被災者を支援する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災者支援情報を提供する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/電話や面談による法律相談を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/避難者への聞き取り調査を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災者を継続的に支援する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/母子家庭と同じサービスを受ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子育て中の母親を雇用する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもたちの将来の土台を作る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/気仙沼に工房を作る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/30人の雇用を生み出す
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/第５回インターナショナル・マイクロファイナンス賞をピースジャムの佐藤賢さんに送る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/三陸復興トモダチ基金の助成を受ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東京電力が損害賠償として１３億１５００万円富岡町に払う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/本来ならば得られるはずだった水道使用料やたばこ税などの減収分を東電が補償する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/避難先での学校・仮庁舎の建設費を東電が補償する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災津波で被害に遭った文化財の救援活動報告の展示会を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災資料の現状報告を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/これまでの文化財救助活動への全国の支援に感謝を表明する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/これからの文化財救援活動への支援を呼びかける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/津波のため塩に浸かった文化財の修復を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/災害研究を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/阪神大震災被災の経験を活かす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災者が他地域に移り住んだ時に地域社会に起こる変化について研究する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/復興庁を被災地に移転する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/各自治体の現状に合わせた支援態勢を取る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/他省庁との調整機能を重視する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/移転の議論で復興を妨げない
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/適切な手法で除染しているかどうかを調査する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/除染現場に環境省職員を配置し、監視を強化す
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/除染に関する通報への省内対応について調査する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/現場責任者に聞き取り調査を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/手抜き除染の再発防止策をまとめる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/スピード感を持って手抜き除染再発防止に対応する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/手抜き除染による汚染に対する国民の不安をなくす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/双葉郡全体の復興
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/双葉郡の人材育成ビジョンを2013年5月に策定
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/復興に向けた育むべき人材像検討
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/復興教育検討
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/人材育成のロードマップ検討
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/毎月会合を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/コウナゴ漁の試験操業を実施する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/緊急雇用事業を受ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/大雪りばぁねっと。の活動を休止する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/大雪りばぁねっと。全従事者の解雇
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/山田町の雇用を確保する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/大雪りばぁねっと。解雇者に雇用保険を給付する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/町に大雪りばぁねっと。停止に関する相談窓口を設ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/大雪りばぁねっと。解雇者に再就職への支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/復興支援予算を受けて事業を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/いわき・ときわ路夢街道キャンペーンを行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/茨城県への観光客を増やす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/茨城、福島両県の観光を盛り上げる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/JR東日本利用客を増やす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/地域の活性化
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/フクシマオーガニックコットンベイブを販売する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/オーガニックコットンプロジェクトに取り組む
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島から安全なものを届ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/和綿の有機栽培を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/和綿から人形を作る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/フクシマオーガニックコットンベイブを買った人がタネを育てて綿をいわき市に送る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/遠隔地の消費者が福島のことを考える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/ブックボーイを再興する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/ブックボーイ駅前本店を再開する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/再建を迷っている人たちに希望を与える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもに被災の映像を見せない
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/子どもに本を買う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/受験用の参考書を買う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/本が売れないなら店を再興しない
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/生活圏に本屋が再開する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/震災・津波による行方不明者を捜索する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/震災・津波による全行方不明者の身元を確認し、遺族に渡す
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/行方不明の家族の行方を知る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/DNA鑑定だけでなく、似顔絵なども活用する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/パトロールを行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/被災者に寄り添った活動を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/復興への希望を音楽に託す
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/若山牧水の「みなかみ紀行」をオペラにする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東北を訪ね歩いた際の体験や、触れ合った被災者の思いを伝える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東北の自然を大切にする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東北の伝統を大切にする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/「東北の人たちへ送る哀歌」を作曲
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東京や新潟で「東北の人たちへ送る哀歌」を演奏する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/牧水の歌に曲を付ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/本店オフィスサービスセンターを福島県に移転する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/原発廃炉に向けた技術開発を行う国際チームを東京に設置する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/賠償についての説明が分かりづらい、対応が遅いとの批判に応える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故で失った消費者の信頼を回復する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/簡潔明瞭、スピード感を持って対応する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/自治会レベルの除染に放射線の知識がある東電社員延べ１０万人を参加させ、協力させる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/賠償や除染業務を本店から福島復興本社に全面移管する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故の賠償責任を果たす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/福島第一原発事故による汚染について除染を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/漂着した船を喜界島で使ってほしい
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/漂着した船を修理する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/モニュメントとして漂着した船を保存する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/震災の悲惨さを伝える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/喜界島島民の防災意識を高める
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/漂着した船が島の人の役にたつ
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/「東日本大震災事業者再生支援機構」の事業再生プログラムの利用を増やす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/事業再生プログラムの認知度を上げる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/事業者に電話をし、事業再生プログラムの利用を促す
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/借金をしたくない
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/説明会や相談会をひらき、事業再生プログラムについて説明する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/借金の一部返済猶予などの支援を受ける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/工場を再開させる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/市の担当者が、事業主に直接アプローチする
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/チリ地震の教訓を生かす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/阪神淡路大震災や、その後の様々な自然災害から得た教訓を生かし、防災教育を推進する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/模型を作り、津波の恐ろしさを伝える
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/宮古市内の小中学校の教員を招いて模型の津波実演をし、防災教育に役立てる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/宮古市内の小中学校で出張防災授業を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災の教訓を生かす
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/模型の作り方や実演方法を普及させる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/さらに多くの地域で実演を行い、防災教育に役立てる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/ぼうさい甲子園に出場する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/ぼうさい甲子園を開催する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/鳥追いの行事を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/えんずのわりの伝統を守る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/えんずのわりの行事を祝う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東松島市宮戸の月浜地区の被災者を元気づける
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/月浜の人たちが笑顔になる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/毎年鳥追いの子どもたちがやってくる
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/秋田市に認知症お年寄りのためののグループホームを作る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/日本家屋の良さを生かしたグループホームを作る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/一軒一軒大工の手作りによる個性がある古い日本家屋で、計約４０部屋をつなぐ新しいグループホームを作る
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東日本大震災による液状化現象によって被災した家屋を移築する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/屋根部分をグループホームのために提供してもらう
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/家部分もグループホームのために提供する
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/液状化で被災した家を壊したくない
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/愛着のある家を秋田で生かしてほしい
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/東京、千葉、岩手からグループホームのための家を集める
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/仙台市が東日本大震災の津波で浸水した災害危険区域外の被災者への住宅再建支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/国が東日本大震災の津波で浸水した災害危険区域外の被災者への住宅再建支援を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/仙台市の財源を仙台市全体のために有効に使う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/仙台市が独自に災害危険区域外の被災者への住宅再建支援金の増額や対象者の拡大を行う
./calc_similarity_i.pl http://data.open-opinion.org/socia/data/Goal/国がもっと早い段階で災害危険区域外の被災者への支援を行う
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/628142c2-e320-41bd-1d6b-0ec0d34b14de
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/a454c816-bf84-af45-92b0-8600c0e9fb87
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/c90ac984-0403-86a9-d765-be72896fccdd
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/3fa2e238-d1c4-f354-d335-b187379816b3
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/a454c816-bf84-af45-92b0-8600c0e9fb87
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/dbc980ad-8264-4981-7946-847895711f50
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/37ac68df-b293-a0e1-2611-d3627ee8c841
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/fee41fbc-53c9-7c8d-3bcf-edcaabed2530
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/43bdc87b-13d5-6158-fca6-6f6218ba7ccb
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/dfb7c5ef-f0cc-36a3-0837-378d656d4341
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/6f401da7-d62a-9746-b2f1-4e807df4ac97
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/5fbc54c1-a8af-d568-b85f-a92107f0fcd0
./calc_similarity_i.pl http://collab.open-opinion.org/resource/Goal/6f401da7-d62a-9746-b2f1-4e807df4ac97

